apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.29.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sidekiq-all
  name: sidekiq-all
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sidekiq-all
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.29.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mastodon-default: "true"
        io.kompose.service: sidekiq-all
    spec:
      nodeSelector:
        role: worker
      containers:
        - args:
            - bundle
            - exec
            - sidekiq
            - -c
            - "5"
          image: ghcr.io/mastodon/mastodon:v4.1.5
          name: sidekiq-all
          resources: {}
          envFrom:
            - secretRef:
                name: mastodon-env
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      restartPolicy: Always
status: {}
