apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml
    kompose.version: 1.29.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sidekiq-pull
  name: sidekiq-pull
spec:
  selector:
    matchLabels:
      io.kompose.service: sidekiq-pull
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml
        kompose.version: 1.29.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mastodon-default: "true"
        io.kompose.service: sidekiq-pull
    spec:
      nodeSelector:
        role: worker
      containers:
        - args:
            - bundle
            - exec
            - sidekiq
            - -c
            - "5"
            - -q
            - pull
            - -q
            - default
            - -q
            - push
            - -q
            - ingress
          image: ghcr.io/mastodon/mastodon:v4.1.8
          name: sidekiq-pull
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 350Mi
          envFrom:
            - secretRef:
                name: mastodon-env
      dnsConfig:
        nameservers:
          - 1.1.1.1
      restartPolicy: Always
status: {}
