apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.29.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: streaming
  name: streaming
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: streaming
  type: LoadBalancer
status:
  # loadBalancer: {}
  loadBalancer:
    ingress:
      - ip: 100.64.1.140
      - ip: 100.64.1.141
      - ip: 100.64.1.142
