apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.29.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: streaming
  name: streaming
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: streaming
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.29.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mastodon-default: "true"
        io.kompose.service: streaming
    spec:
      nodeSelector:
        role: worker
      containers:
        - args:
            - node
            - ./streaming
          image: ghcr.io/mastodon/mastodon:v4.1.5
          # livenessProbe:
          #   exec:
          #     command:
          #       - wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1
          name: streaming
          ports:
            - containerPort: 4000
              hostIP: 0.0.0.0
              hostPort: 4040
              protocol: TCP
          resources: {}
          envFrom:
            - secretRef:
                name: mastodon-env
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      restartPolicy: Always
status: {}
