apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.29.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: web
  type: LoadBalancer
status:
  # loadBalancer: {}
  loadBalancer:
    ingress:
      - ip: 100.64.1.140
      - ip: 100.64.1.141
      - ip: 100.64.1.142
