apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.29.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.29.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mastodon-default: "true"
        io.kompose.service: web
    spec:
      nodeSelector:
        role: worker
      containers:
        - args:
            - bash
            - -c
            - rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000
          image: ghcr.io/mastodon/mastodon:v4.1.5
          # livenessProbe:
          #   exec:
          #     command:
          #       - wget -q --spider --proxy=off localhost:3000/health || exit 1
          name: web
          ports:
            - containerPort: 3000
              hostIP: 0.0.0.0
              # hostPort: 3000
              protocol: TCP
          resources: {}
          envFrom:
            - secretRef:
                name: mastodon-env
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      restartPolicy: Always
status: {}
