apiVersion: v1
kind: PersistentVolume
metadata:
  name: gts-local-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/gts-local-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - raspberrypi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-claim
  labels:
    app: gotosocial
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 25Gi
