apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gts
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 100.64.1.250
    path: /Public/k3s/gts
  mountOptions:
    - nfsvers=3
    - rw
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gts-pv-claim
  labels:
    app: gotosocial
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
