apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gts
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 100.64.1.250
    path: /Public/k3s/gts
  mountOptions:
    - nfsvers=3
    - rw
