---
- name: Update Mastodon Containers on K3s
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Get latest release version
      ansible.builtin.uri:
        url: https://api.github.com/repos/mastodon/mastodon/releases/latest
        return_content: true
      register: mastodon_git

    - name: Display latest version
      ansible.builtin.debug:
        msg: "latest release version is {{ mastodon_git.json.tag_name }}"

    - name: Rewrite version value in ../mastodon/*.yaml and Apply changes with kubectl apply
      ansible.builtin.shell:
        cmd: ../mastodon/verup.sh {{ mastodon_git.json.tag_name }}
